on: push
name: Vivid Angular Run-Build
jobs:
  web-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: npm install, build, and test
      run: |
        npm install --legacy-peer-deps
        echo "$(cat ./.env)"
        export NODE_OPTIONS="--max-old-space-size=4096"
        npm run build
      env:
        CI: false

    - name: FTP SYNC and UPLOAD
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: showcaseangular.vividwebsolutions.in/
        local-dir: dist/

 
        